import type { Metadata } from 'next'
import './globals.css'

import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ja'>
      <body className={`font-serif antialiased`}>{children}</body>
    </html>
  )
}
